project_id = "qddtmaimpnewgebrtwnb"

# Edge function configurations
[functions.send-whatsapp]
verify_jwt = false  # JWT verified in function code for better error handling

[functions.send-guardian-invite]
verify_jwt = false  # JWT verified in function code for better error handling

[functions.send-class-reminders]
verify_jwt = false  # Cron job - uses SERVICE_ROLE_KEY

[functions.analyze-churn-risk]
verify_jwt = false

[functions.check-notification-triggers]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.analyze-attendance]
verify_jwt = false

[functions.generate-ticket]
verify_jwt = false

[functions.export-report]
verify_jwt = false
